### PR TITLE
Adjusted menu width to show Versions tab

### PR DESCRIPTION
**Pull request by thinksanky**
## Description ##
Version Tab was hidden due to extra menus added. Fixed it adding a specific width.

### CODE REVIEW

**Comment by thinksanky** [comment]
screen_shot_2017-12-13_at_10_18_44_pm

**Comment by lupesko** [comment]
Let's make sure this looks good on mobile as well, and paste the screenshot.

**Comment by thinksanky** [comment]
screen shot 2017-12-17 at 4 58 38 pm

**Comment by thinksanky** [comment]
screen shot 2017-12-17 at 4 58 14 pm

**Comment by thinksanky** [comment]
screen shot 2017-12-17 at 5 00 33 pm

**Comment by thinksanky** [comment]
http://ec2-34-235-85-210.compute-1.amazonaws.com:8008 
for testing.

**Comment by lupesko** [comment]
The URL times out for me.
But based on the screenshots looks like you fixed the issue we noticed on mobile.
Ship it!

@sandeep-krishnamurthy @szha

**Comment by lupesko** [comment]
Bouncing again for merge: @sandeep-krishnamurthy @szha

**Pull request merged**
