### PR TITLE
Change to 0.11-RC

### PR DESCRIPTION
**Pull request by kevinthesun**
Only merge this after 0.11-RC released.

### CODE REVIEW

**Comment by lxn2** [comment]
@kevinthesun can you fix these conflicts?

**Comment by kevinthesun** [comment]
I can't fix them, since these conflicts come from nightly build master. Safe way might be wiping asf-site branch and merge this PR.

**Comment by lxn2** [comment]
Does this not list 0.10 as one of the versions? I wiped it out and pushed your changes but tags.txt only has .11

**Comment by kevinthesun** [comment]
No. It should only contains 0.11 and master.

**Comment by lxn2** [comment]
That's not my understanding...did Steffen suggest to delete 0.10 anywhere? I thought we wanted to have all the versions including .10 so far?

**Pull request closed without merging**
