### PR TITLE
fixed version drop down selection menu bar for 0.12.0 and 0.12.1 vers…

### PR DESCRIPTION
**Pull request by thinksanky**
## Description ##
Fixed menu width for remaining versions 0.12.0 and 0.12.1.

### CODE REVIEW

**Comment by thinksanky** [comment]
screen shot 2018-01-10 at 10 04 05 pm

**Comment by thinksanky** [comment]
screen shot 2018-01-10 at 10 03 34 pm

**Comment by thinksanky** [comment]
@sandeep-krishnamurthy , @nswamy 

Please help merge this PR.

**Comment by lupesko** [comment]
Looks good @thinksanky - thanks!
@piiswrong @sandeep-krishnamurthy @nswamy please help review and merge, thanks!

**Comment by sandeep-krishnamurthy** [comment]
@thinksanky - Can you please link here the corresponding changes to mxnet code base? So that following versions have this change?
Please create a tracking github issue, if you want to put this in your pipeline of tasks.

**Comment by szha** [comment]
@marcoabreu would this change in earlier versions be overwritten by nightly job?

**Comment by thinksanky** [comment]
@szha - This change is only for versioned website (Static) which do not run nightly. So they are not changed.

**Pull request merged**
