### PR TITLE
Redirect via mod_rewrite

### PR DESCRIPTION
**Pull request by aaronmarkham**
## Description ##
Even though #57 should have kicked in I'm still seeing a 404 for:
http://mxnet.incubator.apache.org/get_started/install.html

This approach does away with doing meta refresh tags and keeping around dead files. It'll do a proper 301 redirect... assuming mod_rewrite is enabled on the server.

### CODE REVIEW

**Comment by szha** [comment]
Usage of  .htaccess assumes apache http server. If we migrate to static hosting using s3, a different solution will be needed.

**Comment by marcoabreu** [comment]
This entire solution is temporary anyways, considering all these changes
will be reverted once we turn on website generation

Sheng Zha <notifications@github.com> schrieb am Do., 8. März 2018, 23:35:

**Comment by aaronmarkham** [comment]
Well, I was planning on incorporating it in the site generation process. I was thinking the s3 solution was just for staging the site and testing it. For production you would want a web server and its features (I would think).

**Comment by marcoabreu** [comment]
I agree that it's a good solution for the problem in its current form. We
just have to make sure to note down all requirement and revisit all
decisions from scratch without being pressured when creating the new system

Aaron Markham <notifications@github.com> schrieb am Do., 8. März 2018,
23:50:

**Pull request merged**
